language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - DB=mysql
    - DB=pgsql
    - DB=sqlite

matrix:
    allow_failures:
        - php: 7.0

before_install:
    - composer self-update

install:
    - composer install --prefer-source

before_script:
    - mysql -e 'create database test_acl;'
    - psql -c 'create database test_acl;' -U postgres

script:
    - phpunit -v -c Tests/$DB.travis.xml

notifications:
    email:
        - johann.saunier@nuxia.fr
        - alex.dpy@gmail.com
